# -*- coding: utf-8 -*-
"""BDA_Assignment02_S20190020208.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x9AC90g7MgHrxNqcZYTcQAYFGzcMtrsY

<h1>Sales Prediction<h1>
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""# Loading the dataset"""

advertising_data = pd.read_csv("https://raw.githubusercontent.com/chittoorking/BDA_Assignment_02_flask/main/advertising.csv")

advertising_data.head()

advertising_data.shape

advertising_data.info()

#descriptive statistics
advertising_data.describe()

advertising_data.isnull().sum()

import warnings
warnings.filterwarnings('ignore')

# Outlier Analysis
fig, axs = plt.subplots(3, figsize = (5,5))
plt1 = sns.boxplot(advertising_data['TV'], ax = axs[0])
plt2 = sns.boxplot(advertising_data['Newspaper'], ax = axs[1])
plt3 = sns.boxplot(advertising_data['Radio'], ax = axs[2])
plt.tight_layout()

#Visualization to see how Sales are related with other variables using scatter plot.
sns.pairplot(advertising_data, x_vars=['TV', 'Newspaper', 'Radio'], y_vars='Sales', height=4, aspect=1, kind='scatter')
plt.show()

# Let's see the correlation between different variables.
sns.heatmap(advertising_data.corr(), cmap="YlGnBu", annot = True)
plt.show()

"""# The variable TV seems to be most correlated with Sales. So let's go ahead and perform simple linear regression using TV as our feature variable.

# Model Building
"""

X = advertising_data.iloc[:,0:2]
y = advertising_data['Sales']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.7, test_size = 0.3, random_state = 100)

from sklearn.linear_model import LinearRegression
regr = LinearRegression()
  
regr.fit(X_train, y_train)
print(regr.score(X_train, y_train))
print(regr.score(X_test, y_test))

import pickle

pickle.dump(regr, open('model.pkl','wb'))